break_into_partial_movies: false
camera_qualities:
  default_quality: 'medium'
  high:
    frame_rate: 60
    resolution: 1920x1080
  low:
    frame_rate: 15
    resolution: 854x480
  medium:
    frame_rate: 30
    resolution: 1280x720
  ultra_high:
    frame_rate: 60
    resolution: 3840x2160
directories:
  mirror_module_path: false
  output: output
  raster_images: ''
  sounds: ''
  temporary_storage: ''
  vector_images: ''
# style:
#   background_color: ''
#   font: Consolas
style:
  font: "CMU Serif"
  #font: Consolas
  background_color: "#191919"
tex:
  executable: xelatex -no-pdf
  intermediate_filetype: xdv
  template_file: ctex_template.tex
  text_to_replace: '[tex_expression]'
universal_import_line: 'import sys; sys.path.append("."); print("Path updated succesfully.")'
window_position: UR
