##
# Project Title
#
# @file
# @version 0.1

CauchySchwarz:
	manimgl cauchy_schwarz.py CauchySchwarz -w && bash -c "cp output/{CauchySchwarz.txt,videos/CauchySchwarz.mp4} ../reveal/videos"


ProofScene:
	manimgl convex_cones_drawing.py ProofScene -w &&bash -c "cp output/{CauchySchwarz.txt,videos/CauchySchwarz.mp4} ../reveal/videos"



Produce:
 bash -c "cp output/*txt output/*/*mp4 ../reveal/videos "
