##
# Project Title
#
# @file
# @version 0.1

CauchySchwarz:
	manimgl cauchy_schwarz.py CauchySchwarz -w
ProofScene:
	manimgl convex_cones_drawing.py ProofScene -w



Produce:
 bash -c "cp output/*txt output/*/*mp4 ../reveal/videos"
